import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner'
import Card from '../components/card'
import { fetchCoffeeStores } from '../lib/coffee-store'
import styles from '../styles/Home.module.css'


export async function getStaticProps(context) {
  const coffeeStores = await fetchCoffeeStores()
  console.log(coffeeStores)
  return {
    props: {
      coffeeStores
    }
  }
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log("click!!!")
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View one nearby" handleClick={handleOnBannerBtnClick}/>
        <div className={styles.heroImage}>
           <Image src="/static/hero-image.png" alt="" width={800} height={400}/>
        </div>
        {props.coffeeStores.length > 0 && (
        <>
        <h2 className={styles.heading2}>Toronto Stores</h2>
        <br />
        <br />
        <br />
        <div className={styles.cardLayout}>
          {
            props.coffeeStores.map(coffeeStore => {
              return (
              <Card className={styles.card} key={coffeeStore.id} name={coffeeStore.name} imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80"} href={`/coffee-store/${coffeeStore.id}`} />
             )})
          }
        </div>
        </>
        )}
      </main> 
    </div>
  )
}
